In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
X = np.array([
              [1,1],
              [1,2],
              [2,2],
              [2,3]
])

In [4]:
y = np.dot(X,np.array([1,2])) + 3

In [5]:
y

array([ 6,  8,  9, 11])

In [7]:
lr = LinearRegression()

In [8]:
lr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
lr.predict(np.array([[3,5]]))

array([16.])

In [10]:
import pandas as pd

In [13]:
data = pd.read_csv('/content/winequality-red.csv', sep=';')

In [14]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [15]:
lr1 = LinearRegression()

In [17]:
X = data.iloc[:,:11]

In [20]:
y = data.iloc[:,11]

In [21]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [22]:
lr1.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
lr1.predict(X)

array([5.03285045, 5.13787975, 5.20989474, ..., 5.94304255, 5.47075621,
       6.00819633])

In [25]:
lr1.score(X,y)

0.36055170303868833